# Generated by Django 2.0.1 on 2018-08-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20180209_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.IntegerField(choices=[(0, 'Queued'), (1, 'Processing'), (2, 'Success'), (3, 'Error'), (4, 'Aborted'), (5, 'exported')], default=0),
        ),
    ]
