# Generated by Django 2.0.1 on 2018-08-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20180801_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_in', models.IntegerField(null=True)),
                ('frame_out', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='export_list',
            field=models.ManyToManyField(related_name='export_list', to='engine.Export'),
        ),
    ]
