# Generated by Django 2.0.1 on 2018-08-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20180802_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.IntegerField(choices=[(0, 'Queued'), (1, 'Processing'), (2, 'Success'), (3, 'Error'), (4, 'Aborted'), (5, 'Exported')], default=0),
        ),
    ]
